
# SITE SETTINGS
#
# title appears in the header
title: A toolkit for Generative AI, data protection and intellectual property in digital cultural heritage 
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Bootstrap Icons in _includes/bootstrap-icons
# find names on https://icons.getbootstrap.com/ (or look in "_includes/bootstrap-icons")
# some options: code-slash file-code gear tools lightblub book bookmark-star
title-icon: code-slash
# description appears in sidebar footer
description: "Navigate responsibly and ethically in GenAI, copyright and digital cultural heritage"
# keywords for meta tags used by search engines
keywords: "GenAI, copyright, digital cultural heritage"
# image for meta tags, will appear when sharing link on social media
featured-image: "/images/uidaho-workshop.jpg"

# author name, displayed in credits
author: Anna-Maria Sichani 
# year or date published, displayed in sidebar
publication_year: April 2024
# location of code, the full url to your github repository
source-code: https://github.com/SAS-DHRH/GenAI_CCH_toolkit
# content license (typically "cc by-sa"), displayed in sidebar
content_license: "CC BY-SA"
# URL to the content license
content_license_link: https://creativecommons.org/licenses/by-sa/4.0/

##########
# THEME CUSTOMIZATION [optional!]
#
# leave these commented out or blank for defaults.
# these options tweak CSS, so should be valid CSS values.
#
# header-background: 
# header-text-color: 
# breadcrumbs-background: 
# breadcrumbs-text-color: 
# active-nav-color: 
# link-color:
# next-button-color:
# text-color: 
# base-font-size:

##########
# ROBOTS EXCLUDE [optional!]
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


#######
# BUILD SETTINGS [usually leave as is]
#
# Defaults to simplify front matter
defaults:
  - scope:
      path: "content"
    values:
      layout: "content"
# ignore stuff
exclude: [README.md, LICENSE, assets/lib/README.md]
# Build settings
markdown: kramdown
