title: A toolkit for Generative AI, data protection and intellectual property in digital cultural heritage 
title-icon: code-slash
description: "Navigate responsibly and ethically in GenAI, copyright and digital cultural heritage"
keywords: "GenAI, copyright, digital cultural heritage"
featured-image: "/images/AI-toolkit.jpg"
author: Anna-Maria Sichani 
publication_year: 2024
source-code: https://github.com/SAS-DHRH/genai-cch-toolkit
content_license: "CC BY-SA"
content_license_link: https://creativecommons.org/licenses/by-sa/4.0/
defaults:
  - scope:
      path: "content"
    values:
      layout: "content"
# ignore stuff
exclude: [README.md, LICENSE, assets/lib/README.md]
# Build settings
markdown: kramdown
